# Generated by Django 4.2.2 on 2023-08-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('govt', 'Government'), ('private', 'Private')], default='govt', max_length=60)),
            ],
        ),
    ]
