# Generated by Django 4.2.2 on 2023-08-21 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='university',
            new_name='university_ref',
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(choices=[('BCom', 'BCom'), ('BTech', 'BTech'), ('BBA', 'BBA')], max_length=30),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('program_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.program')),
            ],
        ),
    ]
