# Generated by Django 4.2.2 on 2023-08-22 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_university_ref_program_university_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='university',
        ),
    ]
